# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: netcdf package
      run: yum search netcdf
    - name: Test with Maven
      run: mvn -B clean test --file CDL_to_NetCDF_converter/pom.xml -P dev
    - name: Integration Test with maven
      run: mvn -B clean verify --file CDL_to_NetCDF_converter/pom.xml -P integration-test
